// Code generated by "stringer -type ConnState -output connstate_strings_gen.go"; DO NOT EDIT.

package opcua

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Closed-0]
	_ = x[Connected-1]
	_ = x[Connecting-2]
	_ = x[Disconnected-3]
	_ = x[Reconnecting-4]
}

const _ConnState_name = "ClosedConnectedConnectingDisconnectedReconnecting"

var _ConnState_index = [...]uint8{0, 6, 15, 25, 37, 49}

func (i ConnState) String() string {
	if i >= ConnState(len(_ConnState_index)-1) {
		return "ConnState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConnState_name[_ConnState_index[i]:_ConnState_index[i+1]]
}
