// Copyright 2018-2024 opcua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

// Code generated by cmd/id. DO NOT EDIT!

package id

const (
	Boolean                                = 1
	SByte                                  = 2
	Byte                                   = 3
	Int16                                  = 4
	UInt16                                 = 5
	Int32                                  = 6
	UInt32                                 = 7
	Int64                                  = 8
	UInt64                                 = 9
	Float                                  = 10
	Double                                 = 11
	String                                 = 12
	DateTime                               = 13
	GUID                                   = 14
	ByteString                             = 15
	XMLElement                             = 16
	NodeID                                 = 17
	ExpandedNodeID                         = 18
	StatusCode                             = 19
	QualifiedName                          = 20
	LocalizedText                          = 21
	Structure                              = 22
	DataValue                              = 23
	BaseDataType                           = 24
	DiagnosticInfo                         = 25
	Number                                 = 26
	Integer                                = 27
	UInteger                               = 28
	Enumeration                            = 29
	Image                                  = 30
	Decimal                                = 50
	PermissionType                         = 94
	AccessRestrictionType                  = 95
	RolePermissionType                     = 96
	DataTypeDefinition                     = 97
	StructureType                          = 98
	StructureDefinition                    = 99
	EnumDefinition                         = 100
	StructureField                         = 101
	EnumField                              = 102
	NamingRuleType                         = 120
	IDType                                 = 256
	NodeClass                              = 257
	Node                                   = 258
	ObjectNode                             = 261
	ObjectTypeNode                         = 264
	VariableNode                           = 267
	VariableTypeNode                       = 270
	ReferenceTypeNode                      = 273
	MethodNode                             = 276
	ViewNode                               = 279
	DataTypeNode                           = 282
	ReferenceNode                          = 285
	IntegerID                              = 288
	Counter                                = 289
	Duration                               = 290
	NumericRange                           = 291
	UtcTime                                = 294
	LocaleID                               = 295
	Argument                               = 296
	StatusResult                           = 299
	MessageSecurityMode                    = 302
	UserTokenType                          = 303
	UserTokenPolicy                        = 304
	ApplicationType                        = 307
	ApplicationDescription                 = 308
	ApplicationInstanceCertificate         = 311
	EndpointDescription                    = 312
	SecurityTokenRequestType               = 315
	UserIdentityToken                      = 316
	AnonymousIdentityToken                 = 319
	UserNameIdentityToken                  = 322
	X509IdentityToken                      = 325
	EndpointConfiguration                  = 331
	BuildInfo                              = 338
	SignedSoftwareCertificate              = 344
	AttributeWriteMask                     = 347
	NodeAttributesMask                     = 348
	NodeAttributes                         = 349
	ObjectAttributes                       = 352
	VariableAttributes                     = 355
	MethodAttributes                       = 358
	ObjectTypeAttributes                   = 361
	VariableTypeAttributes                 = 364
	ReferenceTypeAttributes                = 367
	DataTypeAttributes                     = 370
	ViewAttributes                         = 373
	AddNodesItem                           = 376
	AddReferencesItem                      = 379
	DeleteNodesItem                        = 382
	DeleteReferencesItem                   = 385
	SessionAuthenticationToken             = 388
	RequestHeader                          = 389
	ResponseHeader                         = 392
	ServiceFault                           = 395
	FindServersRequest                     = 420
	FindServersResponse                    = 423
	GetEndpointsRequest                    = 426
	GetEndpointsResponse                   = 429
	RegisteredServer                       = 432
	RegisterServerRequest                  = 435
	RegisterServerResponse                 = 438
	ChannelSecurityToken                   = 441
	OpenSecureChannelRequest               = 444
	OpenSecureChannelResponse              = 447
	CloseSecureChannelRequest              = 450
	CloseSecureChannelResponse             = 453
	SignatureData                          = 456
	CreateSessionRequest                   = 459
	CreateSessionResponse                  = 462
	ActivateSessionRequest                 = 465
	ActivateSessionResponse                = 468
	CloseSessionRequest                    = 471
	CloseSessionResponse                   = 474
	CancelRequest                          = 477
	CancelResponse                         = 480
	AddNodesResult                         = 483
	AddNodesRequest                        = 486
	AddNodesResponse                       = 489
	AddReferencesRequest                   = 492
	AddReferencesResponse                  = 495
	DeleteNodesRequest                     = 498
	DeleteNodesResponse                    = 501
	DeleteReferencesRequest                = 504
	DeleteReferencesResponse               = 507
	BrowseDirection                        = 510
	ViewDescription                        = 511
	BrowseDescription                      = 514
	BrowseResultMask                       = 517
	ReferenceDescription                   = 518
	ContinuationPoint                      = 521
	BrowseResult                           = 522
	BrowseRequest                          = 525
	BrowseResponse                         = 528
	BrowseNextRequest                      = 531
	BrowseNextResponse                     = 534
	RelativePathElement                    = 537
	RelativePath                           = 540
	BrowsePath                             = 543
	BrowsePathTarget                       = 546
	BrowsePathResult                       = 549
	TranslateBrowsePathsToNodeIDsRequest   = 552
	TranslateBrowsePathsToNodeIDsResponse  = 555
	RegisterNodesRequest                   = 558
	RegisterNodesResponse                  = 561
	UnregisterNodesRequest                 = 564
	UnregisterNodesResponse                = 567
	QueryDataDescription                   = 570
	NodeTypeDescription                    = 573
	FilterOperator                         = 576
	QueryDataSet                           = 577
	NodeReference                          = 580
	ContentFilterElement                   = 583
	ContentFilter                          = 586
	FilterOperand                          = 589
	ElementOperand                         = 592
	LiteralOperand                         = 595
	AttributeOperand                       = 598
	SimpleAttributeOperand                 = 601
	ContentFilterElementResult             = 604
	ContentFilterResult                    = 607
	ParsingResult                          = 610
	QueryFirstRequest                      = 613
	QueryFirstResponse                     = 616
	QueryNextRequest                       = 619
	QueryNextResponse                      = 622
	TimestampsToReturn                     = 625
	ReadValueID                            = 626
	ReadRequest                            = 629
	ReadResponse                           = 632
	HistoryReadValueID                     = 635
	HistoryReadResult                      = 638
	HistoryReadDetails                     = 641
	ReadEventDetails                       = 644
	ReadRawModifiedDetails                 = 647
	ReadProcessedDetails                   = 650
	ReadAtTimeDetails                      = 653
	HistoryData                            = 656
	HistoryEvent                           = 659
	HistoryReadRequest                     = 662
	HistoryReadResponse                    = 665
	WriteValue                             = 668
	WriteRequest                           = 671
	WriteResponse                          = 674
	HistoryUpdateDetails                   = 677
	UpdateDataDetails                      = 680
	UpdateEventDetails                     = 683
	DeleteRawModifiedDetails               = 686
	DeleteAtTimeDetails                    = 689
	DeleteEventDetails                     = 692
	HistoryUpdateResult                    = 695
	HistoryUpdateRequest                   = 698
	HistoryUpdateResponse                  = 701
	CallMethodRequest                      = 704
	CallMethodResult                       = 707
	CallRequest                            = 710
	CallResponse                           = 713
	MonitoringMode                         = 716
	DataChangeTrigger                      = 717
	DeadbandType                           = 718
	MonitoringFilter                       = 719
	DataChangeFilter                       = 722
	EventFilter                            = 725
	AggregateFilter                        = 728
	MonitoringFilterResult                 = 731
	EventFilterResult                      = 734
	AggregateFilterResult                  = 737
	MonitoringParameters                   = 740
	MonitoredItemCreateRequest             = 743
	MonitoredItemCreateResult              = 746
	CreateMonitoredItemsRequest            = 749
	CreateMonitoredItemsResponse           = 752
	MonitoredItemModifyRequest             = 755
	MonitoredItemModifyResult              = 758
	ModifyMonitoredItemsRequest            = 761
	ModifyMonitoredItemsResponse           = 764
	SetMonitoringModeRequest               = 767
	SetMonitoringModeResponse              = 770
	SetTriggeringRequest                   = 773
	SetTriggeringResponse                  = 776
	DeleteMonitoredItemsRequest            = 779
	DeleteMonitoredItemsResponse           = 782
	CreateSubscriptionRequest              = 785
	CreateSubscriptionResponse             = 788
	ModifySubscriptionRequest              = 791
	ModifySubscriptionResponse             = 794
	SetPublishingModeRequest               = 797
	SetPublishingModeResponse              = 800
	NotificationMessage                    = 803
	MonitoredItemNotification              = 806
	DataChangeNotification                 = 809
	StatusChangeNotification               = 818
	SubscriptionAcknowledgement            = 821
	PublishRequest                         = 824
	PublishResponse                        = 827
	RepublishRequest                       = 830
	RepublishResponse                      = 833
	TransferResult                         = 836
	TransferSubscriptionsRequest           = 839
	TransferSubscriptionsResponse          = 842
	DeleteSubscriptionsRequest             = 845
	DeleteSubscriptionsResponse            = 848
	RedundancySupport                      = 851
	ServerState                            = 852
	RedundantServerDataType                = 853
	SamplingIntervalDiagnosticsDataType    = 856
	ServerDiagnosticsSummaryDataType       = 859
	ServerStatusDataType                   = 862
	SessionDiagnosticsDataType             = 865
	SessionSecurityDiagnosticsDataType     = 868
	ServiceCounterDataType                 = 871
	SubscriptionDiagnosticsDataType        = 874
	ModelChangeStructureDataType           = 877
	Range                                  = 884
	EUInformation                          = 887
	ExceptionDeviationFormat               = 890
	Annotation                             = 891
	ProgramDiagnosticDataType              = 894
	SemanticChangeStructureDataType        = 897
	EventNotificationList                  = 914
	EventFieldList                         = 917
	HistoryEventFieldList                  = 920
	IssuedIdentityToken                    = 938
	NotificationData                       = 945
	AggregateConfiguration                 = 948
	ImageBMP                               = 2000
	ImageGIF                               = 2001
	ImageJPG                               = 2002
	ImagePNG                               = 2003
	EnumValueType                          = 7594
	TimeZoneDataType                       = 8912
	ModificationInfo                       = 11216
	HistoryModifiedData                    = 11217
	HistoryUpdateType                      = 11234
	PerformUpdateType                      = 11293
	UpdateStructureDataDetails             = 11295
	BitFieldMaskDataType                   = 11737
	InstanceNode                           = 11879
	TypeNode                               = 11880
	OpenFileMode                           = 11939
	ModelChangeStructureVerbMask           = 11941
	EndpointURLListDataType                = 11943
	NetworkGroupDataType                   = 11944
	AxisScaleEnumeration                   = 12077
	AxisInformation                        = 12079
	XVType                                 = 12080
	ComplexNumberType                      = 12171
	DoubleComplexNumberType                = 12172
	ServerOnNetwork                        = 12189
	FindServersOnNetworkRequest            = 12190
	FindServersOnNetworkResponse           = 12191
	RegisterServer2Request                 = 12193
	RegisterServer2Response                = 12194
	TrustListMasks                         = 12552
	TrustListDataType                      = 12554
	OptionSet                              = 12755
	Union                                  = 12756
	NormalizedString                       = 12877
	DecimalString                          = 12878
	DurationString                         = 12879
	TimeString                             = 12880
	DateString                             = 12881
	DiscoveryConfiguration                 = 12890
	MdnsDiscoveryConfiguration             = 12891
	PublishedVariableDataType              = 14273
	DataSetMetaDataType                    = 14523
	FieldMetaData                          = 14524
	DataTypeDescription                    = 14525
	KeyValuePair                           = 14533
	ConfigurationVersionDataType           = 14593
	PubSubState                            = 14647
	FieldTargetDataType                    = 14744
	SimpleTypeDescription                  = 15005
	UABinaryFileDataType                   = 15006
	BrokerConnectionTransportDataType      = 15007
	BrokerTransportQoS                     = 15008
	AccessLevelType                        = 15031
	EventNotifierType                      = 15033
	AccessLevelExType                      = 15406
	WriterGroupDataType                    = 15480
	StructureDescription                   = 15487
	EnumDescription                        = 15488
	NetworkAddressDataType                 = 15502
	NetworkAddressURLDataType              = 15510
	ReaderGroupDataType                    = 15520
	EndpointType                           = 15528
	PubSubConfigurationDataType            = 15530
	DatagramWriterGroupTransportDataType   = 15532
	DataTypeSchemaHeader                   = 15534
	PublishedDataSetDataType               = 15578
	PublishedDataSetSourceDataType         = 15580
	PublishedDataItemsDataType             = 15581
	PublishedEventsDataType                = 15582
	DataSetFieldContentMask                = 15583
	DataSetWriterDataType                  = 15597
	DataSetWriterTransportDataType         = 15598
	DataSetWriterMessageDataType           = 15605
	PubSubGroupDataType                    = 15609
	WriterGroupTransportDataType           = 15611
	WriterGroupMessageDataType             = 15616
	PubSubConnectionDataType               = 15617
	ConnectionTransportDataType            = 15618
	ReaderGroupTransportDataType           = 15621
	ReaderGroupMessageDataType             = 15622
	DataSetReaderDataType                  = 15623
	DataSetReaderTransportDataType         = 15628
	DataSetReaderMessageDataType           = 15629
	SubscribedDataSetDataType              = 15630
	TargetVariablesDataType                = 15631
	IdentityCriteriaType                   = 15632
	IdentityMappingRuleType                = 15634
	SubscribedDataSetMirrorDataType        = 15635
	UADPNetworkMessageContentMask          = 15642
	UADPWriterGroupMessageDataType         = 15645
	UADPDataSetMessageContentMask          = 15646
	UADPDataSetWriterMessageDataType       = 15652
	UADPDataSetReaderMessageDataType       = 15653
	JSONNetworkMessageContentMask          = 15654
	JSONWriterGroupMessageDataType         = 15657
	JSONDataSetMessageContentMask          = 15658
	JSONDataSetWriterMessageDataType       = 15664
	JSONDataSetReaderMessageDataType       = 15665
	BrokerWriterGroupTransportDataType     = 15667
	BrokerDataSetWriterTransportDataType   = 15669
	BrokerDataSetReaderTransportDataType   = 15670
	OverrideValueHandling                  = 15874
	SessionlessInvokeRequestType           = 15901
	DataSetFieldFlags                      = 15904
	AudioDataType                          = 16307
	AdditionalParametersType               = 16313
	DatagramConnectionTransportDataType    = 17467
	RsaEncryptedSecret                     = 17545
	EccEncryptedSecret                     = 17546
	EphemeralKeyType                       = 17548
	Index                                  = 17588
	GenericAttributeValue                  = 17606
	GenericAttributes                      = 17607
	DecimalDataType                        = 17861
	RationalNumber                         = 18806
	Vector                                 = 18807
	ThreeDVector                           = 18808
	CartesianCoordinates                   = 18809
	ThreeDCartesianCoordinates             = 18810
	Orientation                            = 18811
	ThreeDOrientation                      = 18812
	Frame                                  = 18813
	ThreeDFrame                            = 18814
	DiagnosticsLevel                       = 19723
	PubSubDiagnosticsCounterClassification = 19730
	DataSetOrderingType                    = 20408
	VersionTime                            = 20998
	SessionlessInvokeResponseType          = 20999
	AliasNameDataType                      = 23468
	ReadAnnotationDataDetails              = 23497
	CurrencyUnitType                       = 23498
	TrustListValidationOptions             = 23564
	StandaloneSubscribedDataSetRefDataType = 23599
	StandaloneSubscribedDataSetDataType    = 23600
	SecurityGroupDataType                  = 23601
	PubSubConfiguration2DataType           = 23602
	QosDataType                            = 23603
	TransmitQosDataType                    = 23604
	TransmitQosPriorityDataType            = 23605
	ReceiveQosDataType                     = 23608
	ReceiveQosPriorityDataType             = 23609
	DatagramConnectionTransport2DataType   = 23612
	DatagramWriterGroupTransport2DataType  = 23613
	DatagramDataSetReaderTransportDataType = 23614
	URIString                              = 23751
	ProgramDiagnostic2DataType             = 24033
	PortableQualifiedName                  = 24105
	PortableNodeID                         = 24106
	UnsignedRationalNumber                 = 24107
	Duplex                                 = 24210
	InterfaceAdminStatus                   = 24212
	InterfaceOperStatus                    = 24214
	NegotiationStatus                      = 24216
	TsnFailureCode                         = 24218
	TsnStreamState                         = 24220
	TsnTalkerStatus                        = 24222
	TsnListenerStatus                      = 24224
	SemanticVersionString                  = 24263
	PasswordOptionsMask                    = 24277
	UserConfigurationMask                  = 24279
	UserManagementDataType                 = 24281
	PriorityMappingEntryType               = 25220
	PublishedDataSetCustomSourceDataType   = 25269
	PubSubKeyPushTargetDataType            = 25270
	PubSubConfigurationRefMask             = 25517
	PubSubConfigurationRefDataType         = 25519
	PubSubConfigurationValueDataType       = 25520
	EncodedTicket                          = 25726
	Handle                                 = 31917
	TrimmedString                          = 31918
	AlarmMask                              = 32251
	TransactionErrorType                   = 32285
	ReferenceDescriptionDataType           = 32659
	ReferenceListEntryDataType             = 32660
)

var nameDataType = map[uint32]string{
	1:     "Boolean",
	2:     "SByte",
	3:     "Byte",
	4:     "Int16",
	5:     "UInt16",
	6:     "Int32",
	7:     "UInt32",
	8:     "Int64",
	9:     "UInt64",
	10:    "Float",
	11:    "Double",
	12:    "String",
	13:    "DateTime",
	14:    "GUID",
	15:    "ByteString",
	16:    "XMLElement",
	17:    "NodeID",
	18:    "ExpandedNodeID",
	19:    "StatusCode",
	20:    "QualifiedName",
	21:    "LocalizedText",
	22:    "Structure",
	23:    "DataValue",
	24:    "BaseDataType",
	25:    "DiagnosticInfo",
	26:    "Number",
	27:    "Integer",
	28:    "UInteger",
	29:    "Enumeration",
	30:    "Image",
	50:    "Decimal",
	94:    "PermissionType",
	95:    "AccessRestrictionType",
	96:    "RolePermissionType",
	97:    "DataTypeDefinition",
	98:    "StructureType",
	99:    "StructureDefinition",
	100:   "EnumDefinition",
	101:   "StructureField",
	102:   "EnumField",
	120:   "NamingRuleType",
	256:   "IDType",
	257:   "NodeClass",
	258:   "Node",
	261:   "ObjectNode",
	264:   "ObjectTypeNode",
	267:   "VariableNode",
	270:   "VariableTypeNode",
	273:   "ReferenceTypeNode",
	276:   "MethodNode",
	279:   "ViewNode",
	282:   "DataTypeNode",
	285:   "ReferenceNode",
	288:   "IntegerID",
	289:   "Counter",
	290:   "Duration",
	291:   "NumericRange",
	294:   "UtcTime",
	295:   "LocaleID",
	296:   "Argument",
	299:   "StatusResult",
	302:   "MessageSecurityMode",
	303:   "UserTokenType",
	304:   "UserTokenPolicy",
	307:   "ApplicationType",
	308:   "ApplicationDescription",
	311:   "ApplicationInstanceCertificate",
	312:   "EndpointDescription",
	315:   "SecurityTokenRequestType",
	316:   "UserIdentityToken",
	319:   "AnonymousIdentityToken",
	322:   "UserNameIdentityToken",
	325:   "X509IdentityToken",
	331:   "EndpointConfiguration",
	338:   "BuildInfo",
	344:   "SignedSoftwareCertificate",
	347:   "AttributeWriteMask",
	348:   "NodeAttributesMask",
	349:   "NodeAttributes",
	352:   "ObjectAttributes",
	355:   "VariableAttributes",
	358:   "MethodAttributes",
	361:   "ObjectTypeAttributes",
	364:   "VariableTypeAttributes",
	367:   "ReferenceTypeAttributes",
	370:   "DataTypeAttributes",
	373:   "ViewAttributes",
	376:   "AddNodesItem",
	379:   "AddReferencesItem",
	382:   "DeleteNodesItem",
	385:   "DeleteReferencesItem",
	388:   "SessionAuthenticationToken",
	389:   "RequestHeader",
	392:   "ResponseHeader",
	395:   "ServiceFault",
	420:   "FindServersRequest",
	423:   "FindServersResponse",
	426:   "GetEndpointsRequest",
	429:   "GetEndpointsResponse",
	432:   "RegisteredServer",
	435:   "RegisterServerRequest",
	438:   "RegisterServerResponse",
	441:   "ChannelSecurityToken",
	444:   "OpenSecureChannelRequest",
	447:   "OpenSecureChannelResponse",
	450:   "CloseSecureChannelRequest",
	453:   "CloseSecureChannelResponse",
	456:   "SignatureData",
	459:   "CreateSessionRequest",
	462:   "CreateSessionResponse",
	465:   "ActivateSessionRequest",
	468:   "ActivateSessionResponse",
	471:   "CloseSessionRequest",
	474:   "CloseSessionResponse",
	477:   "CancelRequest",
	480:   "CancelResponse",
	483:   "AddNodesResult",
	486:   "AddNodesRequest",
	489:   "AddNodesResponse",
	492:   "AddReferencesRequest",
	495:   "AddReferencesResponse",
	498:   "DeleteNodesRequest",
	501:   "DeleteNodesResponse",
	504:   "DeleteReferencesRequest",
	507:   "DeleteReferencesResponse",
	510:   "BrowseDirection",
	511:   "ViewDescription",
	514:   "BrowseDescription",
	517:   "BrowseResultMask",
	518:   "ReferenceDescription",
	521:   "ContinuationPoint",
	522:   "BrowseResult",
	525:   "BrowseRequest",
	528:   "BrowseResponse",
	531:   "BrowseNextRequest",
	534:   "BrowseNextResponse",
	537:   "RelativePathElement",
	540:   "RelativePath",
	543:   "BrowsePath",
	546:   "BrowsePathTarget",
	549:   "BrowsePathResult",
	552:   "TranslateBrowsePathsToNodeIDsRequest",
	555:   "TranslateBrowsePathsToNodeIDsResponse",
	558:   "RegisterNodesRequest",
	561:   "RegisterNodesResponse",
	564:   "UnregisterNodesRequest",
	567:   "UnregisterNodesResponse",
	570:   "QueryDataDescription",
	573:   "NodeTypeDescription",
	576:   "FilterOperator",
	577:   "QueryDataSet",
	580:   "NodeReference",
	583:   "ContentFilterElement",
	586:   "ContentFilter",
	589:   "FilterOperand",
	592:   "ElementOperand",
	595:   "LiteralOperand",
	598:   "AttributeOperand",
	601:   "SimpleAttributeOperand",
	604:   "ContentFilterElementResult",
	607:   "ContentFilterResult",
	610:   "ParsingResult",
	613:   "QueryFirstRequest",
	616:   "QueryFirstResponse",
	619:   "QueryNextRequest",
	622:   "QueryNextResponse",
	625:   "TimestampsToReturn",
	626:   "ReadValueID",
	629:   "ReadRequest",
	632:   "ReadResponse",
	635:   "HistoryReadValueID",
	638:   "HistoryReadResult",
	641:   "HistoryReadDetails",
	644:   "ReadEventDetails",
	647:   "ReadRawModifiedDetails",
	650:   "ReadProcessedDetails",
	653:   "ReadAtTimeDetails",
	656:   "HistoryData",
	659:   "HistoryEvent",
	662:   "HistoryReadRequest",
	665:   "HistoryReadResponse",
	668:   "WriteValue",
	671:   "WriteRequest",
	674:   "WriteResponse",
	677:   "HistoryUpdateDetails",
	680:   "UpdateDataDetails",
	683:   "UpdateEventDetails",
	686:   "DeleteRawModifiedDetails",
	689:   "DeleteAtTimeDetails",
	692:   "DeleteEventDetails",
	695:   "HistoryUpdateResult",
	698:   "HistoryUpdateRequest",
	701:   "HistoryUpdateResponse",
	704:   "CallMethodRequest",
	707:   "CallMethodResult",
	710:   "CallRequest",
	713:   "CallResponse",
	716:   "MonitoringMode",
	717:   "DataChangeTrigger",
	718:   "DeadbandType",
	719:   "MonitoringFilter",
	722:   "DataChangeFilter",
	725:   "EventFilter",
	728:   "AggregateFilter",
	731:   "MonitoringFilterResult",
	734:   "EventFilterResult",
	737:   "AggregateFilterResult",
	740:   "MonitoringParameters",
	743:   "MonitoredItemCreateRequest",
	746:   "MonitoredItemCreateResult",
	749:   "CreateMonitoredItemsRequest",
	752:   "CreateMonitoredItemsResponse",
	755:   "MonitoredItemModifyRequest",
	758:   "MonitoredItemModifyResult",
	761:   "ModifyMonitoredItemsRequest",
	764:   "ModifyMonitoredItemsResponse",
	767:   "SetMonitoringModeRequest",
	770:   "SetMonitoringModeResponse",
	773:   "SetTriggeringRequest",
	776:   "SetTriggeringResponse",
	779:   "DeleteMonitoredItemsRequest",
	782:   "DeleteMonitoredItemsResponse",
	785:   "CreateSubscriptionRequest",
	788:   "CreateSubscriptionResponse",
	791:   "ModifySubscriptionRequest",
	794:   "ModifySubscriptionResponse",
	797:   "SetPublishingModeRequest",
	800:   "SetPublishingModeResponse",
	803:   "NotificationMessage",
	806:   "MonitoredItemNotification",
	809:   "DataChangeNotification",
	818:   "StatusChangeNotification",
	821:   "SubscriptionAcknowledgement",
	824:   "PublishRequest",
	827:   "PublishResponse",
	830:   "RepublishRequest",
	833:   "RepublishResponse",
	836:   "TransferResult",
	839:   "TransferSubscriptionsRequest",
	842:   "TransferSubscriptionsResponse",
	845:   "DeleteSubscriptionsRequest",
	848:   "DeleteSubscriptionsResponse",
	851:   "RedundancySupport",
	852:   "ServerState",
	853:   "RedundantServerDataType",
	856:   "SamplingIntervalDiagnosticsDataType",
	859:   "ServerDiagnosticsSummaryDataType",
	862:   "ServerStatusDataType",
	865:   "SessionDiagnosticsDataType",
	868:   "SessionSecurityDiagnosticsDataType",
	871:   "ServiceCounterDataType",
	874:   "SubscriptionDiagnosticsDataType",
	877:   "ModelChangeStructureDataType",
	884:   "Range",
	887:   "EUInformation",
	890:   "ExceptionDeviationFormat",
	891:   "Annotation",
	894:   "ProgramDiagnosticDataType",
	897:   "SemanticChangeStructureDataType",
	914:   "EventNotificationList",
	917:   "EventFieldList",
	920:   "HistoryEventFieldList",
	938:   "IssuedIdentityToken",
	945:   "NotificationData",
	948:   "AggregateConfiguration",
	2000:  "ImageBMP",
	2001:  "ImageGIF",
	2002:  "ImageJPG",
	2003:  "ImagePNG",
	7594:  "EnumValueType",
	8912:  "TimeZoneDataType",
	11216: "ModificationInfo",
	11217: "HistoryModifiedData",
	11234: "HistoryUpdateType",
	11293: "PerformUpdateType",
	11295: "UpdateStructureDataDetails",
	11737: "BitFieldMaskDataType",
	11879: "InstanceNode",
	11880: "TypeNode",
	11939: "OpenFileMode",
	11941: "ModelChangeStructureVerbMask",
	11943: "EndpointURLListDataType",
	11944: "NetworkGroupDataType",
	12077: "AxisScaleEnumeration",
	12079: "AxisInformation",
	12080: "XVType",
	12171: "ComplexNumberType",
	12172: "DoubleComplexNumberType",
	12189: "ServerOnNetwork",
	12190: "FindServersOnNetworkRequest",
	12191: "FindServersOnNetworkResponse",
	12193: "RegisterServer2Request",
	12194: "RegisterServer2Response",
	12552: "TrustListMasks",
	12554: "TrustListDataType",
	12755: "OptionSet",
	12756: "Union",
	12877: "NormalizedString",
	12878: "DecimalString",
	12879: "DurationString",
	12880: "TimeString",
	12881: "DateString",
	12890: "DiscoveryConfiguration",
	12891: "MdnsDiscoveryConfiguration",
	14273: "PublishedVariableDataType",
	14523: "DataSetMetaDataType",
	14524: "FieldMetaData",
	14525: "DataTypeDescription",
	14533: "KeyValuePair",
	14593: "ConfigurationVersionDataType",
	14647: "PubSubState",
	14744: "FieldTargetDataType",
	15005: "SimpleTypeDescription",
	15006: "UABinaryFileDataType",
	15007: "BrokerConnectionTransportDataType",
	15008: "BrokerTransportQoS",
	15031: "AccessLevelType",
	15033: "EventNotifierType",
	15406: "AccessLevelExType",
	15480: "WriterGroupDataType",
	15487: "StructureDescription",
	15488: "EnumDescription",
	15502: "NetworkAddressDataType",
	15510: "NetworkAddressURLDataType",
	15520: "ReaderGroupDataType",
	15528: "EndpointType",
	15530: "PubSubConfigurationDataType",
	15532: "DatagramWriterGroupTransportDataType",
	15534: "DataTypeSchemaHeader",
	15578: "PublishedDataSetDataType",
	15580: "PublishedDataSetSourceDataType",
	15581: "PublishedDataItemsDataType",
	15582: "PublishedEventsDataType",
	15583: "DataSetFieldContentMask",
	15597: "DataSetWriterDataType",
	15598: "DataSetWriterTransportDataType",
	15605: "DataSetWriterMessageDataType",
	15609: "PubSubGroupDataType",
	15611: "WriterGroupTransportDataType",
	15616: "WriterGroupMessageDataType",
	15617: "PubSubConnectionDataType",
	15618: "ConnectionTransportDataType",
	15621: "ReaderGroupTransportDataType",
	15622: "ReaderGroupMessageDataType",
	15623: "DataSetReaderDataType",
	15628: "DataSetReaderTransportDataType",
	15629: "DataSetReaderMessageDataType",
	15630: "SubscribedDataSetDataType",
	15631: "TargetVariablesDataType",
	15632: "IdentityCriteriaType",
	15634: "IdentityMappingRuleType",
	15635: "SubscribedDataSetMirrorDataType",
	15642: "UADPNetworkMessageContentMask",
	15645: "UADPWriterGroupMessageDataType",
	15646: "UADPDataSetMessageContentMask",
	15652: "UADPDataSetWriterMessageDataType",
	15653: "UADPDataSetReaderMessageDataType",
	15654: "JSONNetworkMessageContentMask",
	15657: "JSONWriterGroupMessageDataType",
	15658: "JSONDataSetMessageContentMask",
	15664: "JSONDataSetWriterMessageDataType",
	15665: "JSONDataSetReaderMessageDataType",
	15667: "BrokerWriterGroupTransportDataType",
	15669: "BrokerDataSetWriterTransportDataType",
	15670: "BrokerDataSetReaderTransportDataType",
	15874: "OverrideValueHandling",
	15901: "SessionlessInvokeRequestType",
	15904: "DataSetFieldFlags",
	16307: "AudioDataType",
	16313: "AdditionalParametersType",
	17467: "DatagramConnectionTransportDataType",
	17545: "RsaEncryptedSecret",
	17546: "EccEncryptedSecret",
	17548: "EphemeralKeyType",
	17588: "Index",
	17606: "GenericAttributeValue",
	17607: "GenericAttributes",
	17861: "DecimalDataType",
	18806: "RationalNumber",
	18807: "Vector",
	18808: "ThreeDVector",
	18809: "CartesianCoordinates",
	18810: "ThreeDCartesianCoordinates",
	18811: "Orientation",
	18812: "ThreeDOrientation",
	18813: "Frame",
	18814: "ThreeDFrame",
	19723: "DiagnosticsLevel",
	19730: "PubSubDiagnosticsCounterClassification",
	20408: "DataSetOrderingType",
	20998: "VersionTime",
	20999: "SessionlessInvokeResponseType",
	23468: "AliasNameDataType",
	23497: "ReadAnnotationDataDetails",
	23498: "CurrencyUnitType",
	23564: "TrustListValidationOptions",
	23599: "StandaloneSubscribedDataSetRefDataType",
	23600: "StandaloneSubscribedDataSetDataType",
	23601: "SecurityGroupDataType",
	23602: "PubSubConfiguration2DataType",
	23603: "QosDataType",
	23604: "TransmitQosDataType",
	23605: "TransmitQosPriorityDataType",
	23608: "ReceiveQosDataType",
	23609: "ReceiveQosPriorityDataType",
	23612: "DatagramConnectionTransport2DataType",
	23613: "DatagramWriterGroupTransport2DataType",
	23614: "DatagramDataSetReaderTransportDataType",
	23751: "URIString",
	24033: "ProgramDiagnostic2DataType",
	24105: "PortableQualifiedName",
	24106: "PortableNodeID",
	24107: "UnsignedRationalNumber",
	24210: "Duplex",
	24212: "InterfaceAdminStatus",
	24214: "InterfaceOperStatus",
	24216: "NegotiationStatus",
	24218: "TsnFailureCode",
	24220: "TsnStreamState",
	24222: "TsnTalkerStatus",
	24224: "TsnListenerStatus",
	24263: "SemanticVersionString",
	24277: "PasswordOptionsMask",
	24279: "UserConfigurationMask",
	24281: "UserManagementDataType",
	25220: "PriorityMappingEntryType",
	25269: "PublishedDataSetCustomSourceDataType",
	25270: "PubSubKeyPushTargetDataType",
	25517: "PubSubConfigurationRefMask",
	25519: "PubSubConfigurationRefDataType",
	25520: "PubSubConfigurationValueDataType",
	25726: "EncodedTicket",
	31917: "Handle",
	31918: "TrimmedString",
	32251: "AlarmMask",
	32285: "TransactionErrorType",
	32659: "ReferenceDescriptionDataType",
	32660: "ReferenceListEntryDataType",
}
