// Copyright 2018-2024 opcua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

// Code generated by cmd/id. DO NOT EDIT!

package id

import "strconv"

func Name(id uint32) string {
	if s, ok := nameDataType[id]; ok {
		return s
	}
	if s, ok := nameReferenceType[id]; ok {
		return s
	}
	if s, ok := nameObjectType[id]; ok {
		return s
	}
	if s, ok := nameVariableType[id]; ok {
		return s
	}
	if s, ok := nameObject[id]; ok {
		return s
	}
	if s, ok := nameVariable[id]; ok {
		return s
	}
	if s, ok := nameMethod[id]; ok {
		return s
	}
	return strconv.FormatUint(uint64(id), 10)
}
