// Copyright 2018-2024 opcua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

// Code generated by cmd/id. DO NOT EDIT!

package id

const (
	BaseObjectType                               = 58
	FolderType                                   = 61
	DataTypeSystemType                           = 75
	DataTypeEncodingType                         = 76
	ModellingRuleType                            = 77
	ServerType                                   = 2004
	ServerCapabilitiesType                       = 2013
	ServerDiagnosticsType                        = 2020
	SessionsDiagnosticsSummaryType               = 2026
	SessionDiagnosticsObjectType                 = 2029
	VendorServerInfoType                         = 2033
	ServerRedundancyType                         = 2034
	TransparentRedundancyType                    = 2036
	NonTransparentRedundancyType                 = 2039
	BaseEventType                                = 2041
	AuditEventType                               = 2052
	AuditSecurityEventType                       = 2058
	AuditChannelEventType                        = 2059
	AuditOpenSecureChannelEventType              = 2060
	AuditSessionEventType                        = 2069
	AuditCreateSessionEventType                  = 2071
	AuditActivateSessionEventType                = 2075
	AuditCancelEventType                         = 2078
	AuditCertificateEventType                    = 2080
	AuditCertificateDataMismatchEventType        = 2082
	AuditCertificateExpiredEventType             = 2085
	AuditCertificateInvalidEventType             = 2086
	AuditCertificateUntrustedEventType           = 2087
	AuditCertificateRevokedEventType             = 2088
	AuditCertificateMismatchEventType            = 2089
	AuditNodeManagementEventType                 = 2090
	AuditAddNodesEventType                       = 2091
	AuditDeleteNodesEventType                    = 2093
	AuditAddReferencesEventType                  = 2095
	AuditDeleteReferencesEventType               = 2097
	AuditUpdateEventType                         = 2099
	AuditWriteUpdateEventType                    = 2100
	AuditHistoryUpdateEventType                  = 2104
	AuditUpdateMethodEventType                   = 2127
	SystemEventType                              = 2130
	DeviceFailureEventType                       = 2131
	BaseModelChangeEventType                     = 2132
	GeneralModelChangeEventType                  = 2133
	StateMachineType                             = 2299
	StateType                                    = 2307
	InitialStateType                             = 2309
	TransitionType                               = 2310
	TransitionEventType                          = 2311
	AuditUpdateStateEventType                    = 2315
	HistoricalDataConfigurationType              = 2318
	HistoryServerCapabilitiesType                = 2330
	AggregateFunctionType                        = 2340
	ProgramTransitionEventType                   = 2378
	ProgramStateMachineType                      = 2391
	SemanticChangeEventType                      = 2738
	AuditURLMismatchEventType                    = 2748
	FiniteStateMachineType                       = 2771
	ConditionType                                = 2782
	RefreshStartEventType                        = 2787
	RefreshEndEventType                          = 2788
	RefreshRequiredEventType                     = 2789
	AuditConditionEventType                      = 2790
	AuditConditionEnableEventType                = 2803
	AuditConditionCommentEventType               = 2829
	DialogConditionType                          = 2830
	AcknowledgeableConditionType                 = 2881
	AlarmConditionType                           = 2915
	ShelvedStateMachineType                      = 2929
	LimitAlarmType                               = 2955
	AuditHistoryEventUpdateEventType             = 2999
	AuditHistoryValueUpdateEventType             = 3006
	AuditHistoryDeleteEventType                  = 3012
	AuditHistoryRawModifyDeleteEventType         = 3014
	AuditHistoryAtTimeDeleteEventType            = 3019
	AuditHistoryEventDeleteEventType             = 3022
	EventQueueOverflowEventType                  = 3035
	ProgramTransitionAuditEventType              = 3806
	AuditConditionRespondEventType               = 8927
	AuditConditionAcknowledgeEventType           = 8944
	AuditConditionConfirmEventType               = 8961
	ExclusiveLimitStateMachineType               = 9318
	ExclusiveLimitAlarmType                      = 9341
	ExclusiveLevelAlarmType                      = 9482
	ExclusiveRateOfChangeAlarmType               = 9623
	ExclusiveDeviationAlarmType                  = 9764
	NonExclusiveLimitAlarmType                   = 9906
	NonExclusiveLevelAlarmType                   = 10060
	NonExclusiveRateOfChangeAlarmType            = 10214
	NonExclusiveDeviationAlarmType               = 10368
	DiscreteAlarmType                            = 10523
	OffNormalAlarmType                           = 10637
	TripAlarmType                                = 10751
	AuditConditionShelvingEventType              = 11093
	BaseConditionClassType                       = 11163
	ProcessConditionClassType                    = 11164
	MaintenanceConditionClassType                = 11165
	SystemConditionClassType                     = 11166
	AggregateConfigurationType                   = 11187
	ProgressEventType                            = 11436
	SystemStatusChangeEventType                  = 11446
	OperationLimitsType                          = 11564
	FileType                                     = 11575
	AddressSpaceFileType                         = 11595
	NamespaceMetadataType                        = 11616
	NamespacesType                               = 11645
	SystemOffNormalAlarmType                     = 11753
	AuditProgramTransitionEventType              = 11856
	NonTransparentNetworkRedundancyType          = 11945
	TrustListType                                = 12522
	CertificateGroupType                         = 12555
	CertificateType                              = 12556
	ApplicationCertificateType                   = 12557
	HttpsCertificateType                         = 12558
	RsaMinApplicationCertificateType             = 12559
	RsaSha256ApplicationCertificateType          = 12560
	TrustListUpdatedAuditEventType               = 12561
	ServerConfigurationType                      = 12581
	CertificateUpdatedAuditEventType             = 12620
	CertificateExpirationAlarmType               = 13225
	FileDirectoryType                            = 13353
	CertificateGroupFolderType                   = 13813
	PubSubConnectionType                         = 14209
	PubSubGroupType                              = 14232
	PublishSubscribeType                         = 14416
	DataSetFolderType                            = 14477
	PublishedDataSetType                         = 14509
	PublishedDataItemsType                       = 14534
	PublishedEventsType                          = 14572
	PubSubStatusType                             = 14643
	AuditConditionResetEventType                 = 15013
	DatagramConnectionTransportType              = 15064
	SubscribedDataSetType                        = 15108
	ChoiceStateType                              = 15109
	TargetVariablesType                          = 15111
	SubscribedDataSetMirrorType                  = 15127
	BrokerConnectionTransportType                = 15155
	UserCredentialCertificateType                = 15181
	DataSetWriterType                            = 15298
	DataSetWriterTransportType                   = 15305
	DataSetReaderType                            = 15306
	DataSetReaderTransportType                   = 15319
	SecurityGroupFolderType                      = 15452
	SecurityGroupType                            = 15471
	ExtensionFieldsType                          = 15489
	PubSubStatusEventType                        = 15535
	PubSubTransportLimitsExceedEventType         = 15548
	PubSubCommunicationFailureEventType          = 15563
	RoleSetType                                  = 15607
	RoleType                                     = 15620
	TemporaryFileTransferType                    = 15744
	FileTransferStateMachineType                 = 15803
	PubSubKeyServiceType                         = 15906
	AlarmGroupType                               = 16405
	DiscrepancyAlarmType                         = 17080
	SafetyConditionClassType                     = 17218
	HighlyManagedAlarmConditionClassType         = 17219
	TrainingConditionClassType                   = 17220
	TestingConditionClassType                    = 17221
	AuditConditionSuppressionEventType           = 17225
	AuditConditionSilenceEventType               = 17242
	AuditConditionOutOfServiceEventType          = 17259
	AlarmMetricsType                             = 17279
	KeyCredentialConfigurationFolderType         = 17496
	DictionaryEntryType                          = 17589
	DictionaryFolderType                         = 17591
	IrdiDictionaryEntryType                      = 17598
	URIDictionaryEntryType                       = 17600
	BaseInterfaceType                            = 17602
	RoleMappingRuleChangedAuditEventType         = 17641
	ConnectionTransportType                      = 17721
	WriterGroupType                              = 17725
	AuthorizationServiceConfigurationType        = 17852
	WriterGroupTransportType                     = 17997
	WriterGroupMessageType                       = 17998
	ReaderGroupType                              = 17999
	KeyCredentialConfigurationType               = 18001
	KeyCredentialAuditEventType                  = 18011
	KeyCredentialUpdatedAuditEventType           = 18029
	KeyCredentialDeletedAuditEventType           = 18047
	InstrumentDiagnosticAlarmType                = 18347
	SystemDiagnosticAlarmType                    = 18496
	StatisticalConditionClassType                = 18665
	AuditHistoryAnnotationUpdateEventType        = 19095
	TrustListOutOfDateAlarmType                  = 19297
	PubSubDiagnosticsType                        = 19677
	PubSubDiagnosticsRootType                    = 19732
	PubSubDiagnosticsConnectionType              = 19786
	PubSubDiagnosticsWriterGroupType             = 19834
	PubSubDiagnosticsReaderGroupType             = 19903
	PubSubDiagnosticsDataSetWriterType           = 19968
	PubSubDiagnosticsDataSetReaderType           = 20027
	ReaderGroupTransportType                     = 21090
	ReaderGroupMessageType                       = 21091
	DataSetWriterMessageType                     = 21096
	DataSetReaderMessageType                     = 21104
	UADPWriterGroupMessageType                   = 21105
	UADPDataSetWriterMessageType                 = 21111
	UADPDataSetReaderMessageType                 = 21116
	JSONWriterGroupMessageType                   = 21126
	JSONDataSetWriterMessageType                 = 21128
	JSONDataSetReaderMessageType                 = 21130
	DatagramWriterGroupTransportType             = 21133
	BrokerWriterGroupTransportType               = 21136
	BrokerDataSetWriterTransportType             = 21138
	BrokerDataSetReaderTransportType             = 21142
	NetworkAddressType                           = 21145
	NetworkAddressURLType                        = 21147
	AliasNameType                                = 23455
	AliasNameCategoryType                        = 23456
	IOrderedObjectType                           = 23513
	OrderedListType                              = 23518
	EccApplicationCertificateType                = 23537
	EccNistP256ApplicationCertificateType        = 23538
	EccNistP384ApplicationCertificateType        = 23539
	EccBrainpoolP256r1ApplicationCertificateType = 23540
	EccBrainpoolP384r1ApplicationCertificateType = 23541
	EccCurve25519ApplicationCertificateType      = 23542
	EccCurve448ApplicationCertificateType        = 23543
	AuthorizationServicesConfigurationFolderType = 23556
	AuditClientEventType                         = 23606
	SubscribedDataSetFolderType                  = 23795
	StandaloneSubscribedDataSetType              = 23828
	PubSubCapabilitiesType                       = 23832
	AuditClientUpdateMethodResultEventType       = 23926
	DatagramDataSetReaderTransportType           = 24016
	IIetfBaseNetworkInterfaceType                = 24148
	IIeeeBaseEthernetPortType                    = 24158
	IBaseEthernetCapabilitiesType                = 24167
	ISrClassType                                 = 24169
	IIeeeBaseTsnStreamType                       = 24173
	IIeeeBaseTsnTrafficSpecificationType         = 24179
	IIeeeBaseTsnStatusStreamType                 = 24183
	IIeeeTsnInterfaceConfigurationType           = 24188
	IIeeeTsnInterfaceConfigurationTalkerType     = 24191
	IIeeeTsnInterfaceConfigurationListenerType   = 24195
	IIeeeTsnMacAddressType                       = 24199
	IIeeeTsnVlanTagType                          = 24202
	IPriorityMappingEntryType                    = 24205
	IIeeeAutoNegotiationStatusType               = 24233
	UserManagementType                           = 24264
	IVlanIDType                                  = 25218
	IetfBaseNetworkInterfaceType                 = 25221
	PriorityMappingTableType                     = 25227
	PubSubKeyPushTargetType                      = 25337
	PubSubKeyPushTargetFolderType                = 25346
	PubSubConfigurationType                      = 25482
	ApplicationConfigurationType                 = 25731
	ProvisionableDeviceType                      = 26871
	AlarmSuppressionGroupType                    = 32064
	TrustListUpdateRequestedAuditEventType       = 32260
	TransactionDiagnosticsType                   = 32286
	CertificateUpdateRequestedAuditEventType     = 32306
)

var nameObjectType = map[uint32]string{
	58:    "BaseObjectType",
	61:    "FolderType",
	75:    "DataTypeSystemType",
	76:    "DataTypeEncodingType",
	77:    "ModellingRuleType",
	2004:  "ServerType",
	2013:  "ServerCapabilitiesType",
	2020:  "ServerDiagnosticsType",
	2026:  "SessionsDiagnosticsSummaryType",
	2029:  "SessionDiagnosticsObjectType",
	2033:  "VendorServerInfoType",
	2034:  "ServerRedundancyType",
	2036:  "TransparentRedundancyType",
	2039:  "NonTransparentRedundancyType",
	2041:  "BaseEventType",
	2052:  "AuditEventType",
	2058:  "AuditSecurityEventType",
	2059:  "AuditChannelEventType",
	2060:  "AuditOpenSecureChannelEventType",
	2069:  "AuditSessionEventType",
	2071:  "AuditCreateSessionEventType",
	2075:  "AuditActivateSessionEventType",
	2078:  "AuditCancelEventType",
	2080:  "AuditCertificateEventType",
	2082:  "AuditCertificateDataMismatchEventType",
	2085:  "AuditCertificateExpiredEventType",
	2086:  "AuditCertificateInvalidEventType",
	2087:  "AuditCertificateUntrustedEventType",
	2088:  "AuditCertificateRevokedEventType",
	2089:  "AuditCertificateMismatchEventType",
	2090:  "AuditNodeManagementEventType",
	2091:  "AuditAddNodesEventType",
	2093:  "AuditDeleteNodesEventType",
	2095:  "AuditAddReferencesEventType",
	2097:  "AuditDeleteReferencesEventType",
	2099:  "AuditUpdateEventType",
	2100:  "AuditWriteUpdateEventType",
	2104:  "AuditHistoryUpdateEventType",
	2127:  "AuditUpdateMethodEventType",
	2130:  "SystemEventType",
	2131:  "DeviceFailureEventType",
	2132:  "BaseModelChangeEventType",
	2133:  "GeneralModelChangeEventType",
	2299:  "StateMachineType",
	2307:  "StateType",
	2309:  "InitialStateType",
	2310:  "TransitionType",
	2311:  "TransitionEventType",
	2315:  "AuditUpdateStateEventType",
	2318:  "HistoricalDataConfigurationType",
	2330:  "HistoryServerCapabilitiesType",
	2340:  "AggregateFunctionType",
	2378:  "ProgramTransitionEventType",
	2391:  "ProgramStateMachineType",
	2738:  "SemanticChangeEventType",
	2748:  "AuditURLMismatchEventType",
	2771:  "FiniteStateMachineType",
	2782:  "ConditionType",
	2787:  "RefreshStartEventType",
	2788:  "RefreshEndEventType",
	2789:  "RefreshRequiredEventType",
	2790:  "AuditConditionEventType",
	2803:  "AuditConditionEnableEventType",
	2829:  "AuditConditionCommentEventType",
	2830:  "DialogConditionType",
	2881:  "AcknowledgeableConditionType",
	2915:  "AlarmConditionType",
	2929:  "ShelvedStateMachineType",
	2955:  "LimitAlarmType",
	2999:  "AuditHistoryEventUpdateEventType",
	3006:  "AuditHistoryValueUpdateEventType",
	3012:  "AuditHistoryDeleteEventType",
	3014:  "AuditHistoryRawModifyDeleteEventType",
	3019:  "AuditHistoryAtTimeDeleteEventType",
	3022:  "AuditHistoryEventDeleteEventType",
	3035:  "EventQueueOverflowEventType",
	3806:  "ProgramTransitionAuditEventType",
	8927:  "AuditConditionRespondEventType",
	8944:  "AuditConditionAcknowledgeEventType",
	8961:  "AuditConditionConfirmEventType",
	9318:  "ExclusiveLimitStateMachineType",
	9341:  "ExclusiveLimitAlarmType",
	9482:  "ExclusiveLevelAlarmType",
	9623:  "ExclusiveRateOfChangeAlarmType",
	9764:  "ExclusiveDeviationAlarmType",
	9906:  "NonExclusiveLimitAlarmType",
	10060: "NonExclusiveLevelAlarmType",
	10214: "NonExclusiveRateOfChangeAlarmType",
	10368: "NonExclusiveDeviationAlarmType",
	10523: "DiscreteAlarmType",
	10637: "OffNormalAlarmType",
	10751: "TripAlarmType",
	11093: "AuditConditionShelvingEventType",
	11163: "BaseConditionClassType",
	11164: "ProcessConditionClassType",
	11165: "MaintenanceConditionClassType",
	11166: "SystemConditionClassType",
	11187: "AggregateConfigurationType",
	11436: "ProgressEventType",
	11446: "SystemStatusChangeEventType",
	11564: "OperationLimitsType",
	11575: "FileType",
	11595: "AddressSpaceFileType",
	11616: "NamespaceMetadataType",
	11645: "NamespacesType",
	11753: "SystemOffNormalAlarmType",
	11856: "AuditProgramTransitionEventType",
	11945: "NonTransparentNetworkRedundancyType",
	12522: "TrustListType",
	12555: "CertificateGroupType",
	12556: "CertificateType",
	12557: "ApplicationCertificateType",
	12558: "HttpsCertificateType",
	12559: "RsaMinApplicationCertificateType",
	12560: "RsaSha256ApplicationCertificateType",
	12561: "TrustListUpdatedAuditEventType",
	12581: "ServerConfigurationType",
	12620: "CertificateUpdatedAuditEventType",
	13225: "CertificateExpirationAlarmType",
	13353: "FileDirectoryType",
	13813: "CertificateGroupFolderType",
	14209: "PubSubConnectionType",
	14232: "PubSubGroupType",
	14416: "PublishSubscribeType",
	14477: "DataSetFolderType",
	14509: "PublishedDataSetType",
	14534: "PublishedDataItemsType",
	14572: "PublishedEventsType",
	14643: "PubSubStatusType",
	15013: "AuditConditionResetEventType",
	15064: "DatagramConnectionTransportType",
	15108: "SubscribedDataSetType",
	15109: "ChoiceStateType",
	15111: "TargetVariablesType",
	15127: "SubscribedDataSetMirrorType",
	15155: "BrokerConnectionTransportType",
	15181: "UserCredentialCertificateType",
	15298: "DataSetWriterType",
	15305: "DataSetWriterTransportType",
	15306: "DataSetReaderType",
	15319: "DataSetReaderTransportType",
	15452: "SecurityGroupFolderType",
	15471: "SecurityGroupType",
	15489: "ExtensionFieldsType",
	15535: "PubSubStatusEventType",
	15548: "PubSubTransportLimitsExceedEventType",
	15563: "PubSubCommunicationFailureEventType",
	15607: "RoleSetType",
	15620: "RoleType",
	15744: "TemporaryFileTransferType",
	15803: "FileTransferStateMachineType",
	15906: "PubSubKeyServiceType",
	16405: "AlarmGroupType",
	17080: "DiscrepancyAlarmType",
	17218: "SafetyConditionClassType",
	17219: "HighlyManagedAlarmConditionClassType",
	17220: "TrainingConditionClassType",
	17221: "TestingConditionClassType",
	17225: "AuditConditionSuppressionEventType",
	17242: "AuditConditionSilenceEventType",
	17259: "AuditConditionOutOfServiceEventType",
	17279: "AlarmMetricsType",
	17496: "KeyCredentialConfigurationFolderType",
	17589: "DictionaryEntryType",
	17591: "DictionaryFolderType",
	17598: "IrdiDictionaryEntryType",
	17600: "URIDictionaryEntryType",
	17602: "BaseInterfaceType",
	17641: "RoleMappingRuleChangedAuditEventType",
	17721: "ConnectionTransportType",
	17725: "WriterGroupType",
	17852: "AuthorizationServiceConfigurationType",
	17997: "WriterGroupTransportType",
	17998: "WriterGroupMessageType",
	17999: "ReaderGroupType",
	18001: "KeyCredentialConfigurationType",
	18011: "KeyCredentialAuditEventType",
	18029: "KeyCredentialUpdatedAuditEventType",
	18047: "KeyCredentialDeletedAuditEventType",
	18347: "InstrumentDiagnosticAlarmType",
	18496: "SystemDiagnosticAlarmType",
	18665: "StatisticalConditionClassType",
	19095: "AuditHistoryAnnotationUpdateEventType",
	19297: "TrustListOutOfDateAlarmType",
	19677: "PubSubDiagnosticsType",
	19732: "PubSubDiagnosticsRootType",
	19786: "PubSubDiagnosticsConnectionType",
	19834: "PubSubDiagnosticsWriterGroupType",
	19903: "PubSubDiagnosticsReaderGroupType",
	19968: "PubSubDiagnosticsDataSetWriterType",
	20027: "PubSubDiagnosticsDataSetReaderType",
	21090: "ReaderGroupTransportType",
	21091: "ReaderGroupMessageType",
	21096: "DataSetWriterMessageType",
	21104: "DataSetReaderMessageType",
	21105: "UADPWriterGroupMessageType",
	21111: "UADPDataSetWriterMessageType",
	21116: "UADPDataSetReaderMessageType",
	21126: "JSONWriterGroupMessageType",
	21128: "JSONDataSetWriterMessageType",
	21130: "JSONDataSetReaderMessageType",
	21133: "DatagramWriterGroupTransportType",
	21136: "BrokerWriterGroupTransportType",
	21138: "BrokerDataSetWriterTransportType",
	21142: "BrokerDataSetReaderTransportType",
	21145: "NetworkAddressType",
	21147: "NetworkAddressURLType",
	23455: "AliasNameType",
	23456: "AliasNameCategoryType",
	23513: "IOrderedObjectType",
	23518: "OrderedListType",
	23537: "EccApplicationCertificateType",
	23538: "EccNistP256ApplicationCertificateType",
	23539: "EccNistP384ApplicationCertificateType",
	23540: "EccBrainpoolP256r1ApplicationCertificateType",
	23541: "EccBrainpoolP384r1ApplicationCertificateType",
	23542: "EccCurve25519ApplicationCertificateType",
	23543: "EccCurve448ApplicationCertificateType",
	23556: "AuthorizationServicesConfigurationFolderType",
	23606: "AuditClientEventType",
	23795: "SubscribedDataSetFolderType",
	23828: "StandaloneSubscribedDataSetType",
	23832: "PubSubCapabilitiesType",
	23926: "AuditClientUpdateMethodResultEventType",
	24016: "DatagramDataSetReaderTransportType",
	24148: "IIetfBaseNetworkInterfaceType",
	24158: "IIeeeBaseEthernetPortType",
	24167: "IBaseEthernetCapabilitiesType",
	24169: "ISrClassType",
	24173: "IIeeeBaseTsnStreamType",
	24179: "IIeeeBaseTsnTrafficSpecificationType",
	24183: "IIeeeBaseTsnStatusStreamType",
	24188: "IIeeeTsnInterfaceConfigurationType",
	24191: "IIeeeTsnInterfaceConfigurationTalkerType",
	24195: "IIeeeTsnInterfaceConfigurationListenerType",
	24199: "IIeeeTsnMacAddressType",
	24202: "IIeeeTsnVlanTagType",
	24205: "IPriorityMappingEntryType",
	24233: "IIeeeAutoNegotiationStatusType",
	24264: "UserManagementType",
	25218: "IVlanIDType",
	25221: "IetfBaseNetworkInterfaceType",
	25227: "PriorityMappingTableType",
	25337: "PubSubKeyPushTargetType",
	25346: "PubSubKeyPushTargetFolderType",
	25482: "PubSubConfigurationType",
	25731: "ApplicationConfigurationType",
	26871: "ProvisionableDeviceType",
	32064: "AlarmSuppressionGroupType",
	32260: "TrustListUpdateRequestedAuditEventType",
	32286: "TransactionDiagnosticsType",
	32306: "CertificateUpdateRequestedAuditEventType",
}
