// Copyright 2018-2024 opcua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

// Code generated by cmd/id. DO NOT EDIT!

package id

const (
	References                          = 31
	NonHierarchicalReferences           = 32
	HierarchicalReferences              = 33
	HasChild                            = 34
	Organizes                           = 35
	HasEventSource                      = 36
	HasModellingRule                    = 37
	HasEncoding                         = 38
	HasDescription                      = 39
	HasTypeDefinition                   = 40
	GeneratesEvent                      = 41
	Aggregates                          = 44
	HasSubtype                          = 45
	HasProperty                         = 46
	HasComponent                        = 47
	HasNotifier                         = 48
	HasOrderedComponent                 = 49
	FromState                           = 51
	ToState                             = 52
	HasCause                            = 53
	HasEffect                           = 54
	HasHistoricalConfiguration          = 56
	HasSubStateMachine                  = 117
	HasArgumentDescription              = 129
	HasOptionalInputArgumentDescription = 131
	AlwaysGeneratesEvent                = 3065
	HasTrueSubState                     = 9004
	HasFalseSubState                    = 9005
	HasCondition                        = 9006
	HasPubSubConnection                 = 14476
	DataSetToWriter                     = 14936
	HasGuard                            = 15112
	HasDataSetWriter                    = 15296
	HasDataSetReader                    = 15297
	HasAlarmSuppressionGroup            = 16361
	AlarmGroupMember                    = 16362
	HasEffectDisable                    = 17276
	HasDictionaryEntry                  = 17597
	HasInterface                        = 17603
	HasAddIn                            = 17604
	HasEffectEnable                     = 17983
	HasEffectSuppressed                 = 17984
	HasEffectUnsuppressed               = 17985
	HasWriterGroup                      = 18804
	HasReaderGroup                      = 18805
	AliasFor                            = 23469
	IsDeprecated                        = 23562
	HasStructuredComponent              = 24136
	AssociatedWith                      = 24137
	UsesPriorityMappingTable            = 25237
	HasLowerLayerInterface              = 25238
	IsExecutableOn                      = 25253
	Controls                            = 25254
	Utilizes                            = 25255
	Requires                            = 25256
	IsPhysicallyConnectedTo             = 25257
	RepresentsSameEntityAs              = 25258
	RepresentsSameHardwareAs            = 25259
	RepresentsSameFunctionalityAs       = 25260
	IsHostedBy                          = 25261
	HasPhysicalComponent                = 25262
	HasContainedComponent               = 25263
	HasAttachedComponent                = 25264
	IsExecutingOn                       = 25265
	HasPushedSecurityGroup              = 25345
	AlarmSuppressionGroupMember         = 32059
	HasReferenceDescription             = 32679
)

var nameReferenceType = map[uint32]string{
	31:    "References",
	32:    "NonHierarchicalReferences",
	33:    "HierarchicalReferences",
	34:    "HasChild",
	35:    "Organizes",
	36:    "HasEventSource",
	37:    "HasModellingRule",
	38:    "HasEncoding",
	39:    "HasDescription",
	40:    "HasTypeDefinition",
	41:    "GeneratesEvent",
	44:    "Aggregates",
	45:    "HasSubtype",
	46:    "HasProperty",
	47:    "HasComponent",
	48:    "HasNotifier",
	49:    "HasOrderedComponent",
	51:    "FromState",
	52:    "ToState",
	53:    "HasCause",
	54:    "HasEffect",
	56:    "HasHistoricalConfiguration",
	117:   "HasSubStateMachine",
	129:   "HasArgumentDescription",
	131:   "HasOptionalInputArgumentDescription",
	3065:  "AlwaysGeneratesEvent",
	9004:  "HasTrueSubState",
	9005:  "HasFalseSubState",
	9006:  "HasCondition",
	14476: "HasPubSubConnection",
	14936: "DataSetToWriter",
	15112: "HasGuard",
	15296: "HasDataSetWriter",
	15297: "HasDataSetReader",
	16361: "HasAlarmSuppressionGroup",
	16362: "AlarmGroupMember",
	17276: "HasEffectDisable",
	17597: "HasDictionaryEntry",
	17603: "HasInterface",
	17604: "HasAddIn",
	17983: "HasEffectEnable",
	17984: "HasEffectSuppressed",
	17985: "HasEffectUnsuppressed",
	18804: "HasWriterGroup",
	18805: "HasReaderGroup",
	23469: "AliasFor",
	23562: "IsDeprecated",
	24136: "HasStructuredComponent",
	24137: "AssociatedWith",
	25237: "UsesPriorityMappingTable",
	25238: "HasLowerLayerInterface",
	25253: "IsExecutableOn",
	25254: "Controls",
	25255: "Utilizes",
	25256: "Requires",
	25257: "IsPhysicallyConnectedTo",
	25258: "RepresentsSameEntityAs",
	25259: "RepresentsSameHardwareAs",
	25260: "RepresentsSameFunctionalityAs",
	25261: "IsHostedBy",
	25262: "HasPhysicalComponent",
	25263: "HasContainedComponent",
	25264: "HasAttachedComponent",
	25265: "IsExecutingOn",
	25345: "HasPushedSecurityGroup",
	32059: "AlarmSuppressionGroupMember",
	32679: "HasReferenceDescription",
}
