// Copyright 2018-2024 opcua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

// Code generated by cmd/id. DO NOT EDIT!

package id

const (
	BaseVariableType                          = 62
	BaseDataVariableType                      = 63
	PropertyType                              = 68
	DataTypeDescriptionType                   = 69
	DataTypeDictionaryType                    = 72
	ServerVendorCapabilityType                = 2137
	ServerStatusType                          = 2138
	ServerDiagnosticsSummaryType              = 2150
	SamplingIntervalDiagnosticsArrayType      = 2164
	SamplingIntervalDiagnosticsType           = 2165
	SubscriptionDiagnosticsArrayType          = 2171
	SubscriptionDiagnosticsType               = 2172
	SessionDiagnosticsArrayType               = 2196
	SessionDiagnosticsVariableType            = 2197
	SessionSecurityDiagnosticsArrayType       = 2243
	SessionSecurityDiagnosticsType            = 2244
	DataItemType                              = 2365
	AnalogItemType                            = 2368
	DiscreteItemType                          = 2372
	TwoStateDiscreteType                      = 2373
	MultiStateDiscreteType                    = 2376
	ProgramDiagnosticType                     = 2380
	StateVariableType                         = 2755
	FiniteStateVariableType                   = 2760
	TransitionVariableType                    = 2762
	FiniteTransitionVariableType              = 2767
	BuildInfoType                             = 3051
	TwoStateVariableType                      = 8995
	ConditionVariableType                     = 9002
	MultiStateValueDiscreteType               = 11238
	OptionSetType                             = 11487
	ArrayItemType                             = 12021
	YArrayItemType                            = 12029
	XYArrayItemType                           = 12038
	ImageItemType                             = 12047
	CubeItemType                              = 12057
	NDimensionArrayItemType                   = 12068
	GuardVariableType                         = 15113
	ExpressionGuardVariableType               = 15128
	ElseGuardVariableType                     = 15317
	BaseAnalogType                            = 15318
	ProgramDiagnostic2Type                    = 15383
	SelectionListType                         = 16309
	AlarmRateVariableType                     = 17277
	AnalogUnitType                            = 17497
	AnalogUnitRangeType                       = 17570
	RationalNumberType                        = 17709
	VectorType                                = 17714
	ThreeDVectorType                          = 17716
	AudioVariableType                         = 17986
	CartesianCoordinatesType                  = 18772
	ThreeDCartesianCoordinatesType            = 18774
	OrientationType                           = 18779
	ThreeDOrientationType                     = 18781
	FrameType                                 = 18786
	ThreeDFrameType                           = 18791
	MultiStateDictionaryEntryDiscreteBaseType = 19077
	MultiStateDictionaryEntryDiscreteType     = 19084
	PubSubDiagnosticsCounterType              = 19725
	AlarmStateVariableType                    = 32244
	ReferenceDescriptionVariableType          = 32657
)

var nameVariableType = map[uint32]string{
	62:    "BaseVariableType",
	63:    "BaseDataVariableType",
	68:    "PropertyType",
	69:    "DataTypeDescriptionType",
	72:    "DataTypeDictionaryType",
	2137:  "ServerVendorCapabilityType",
	2138:  "ServerStatusType",
	2150:  "ServerDiagnosticsSummaryType",
	2164:  "SamplingIntervalDiagnosticsArrayType",
	2165:  "SamplingIntervalDiagnosticsType",
	2171:  "SubscriptionDiagnosticsArrayType",
	2172:  "SubscriptionDiagnosticsType",
	2196:  "SessionDiagnosticsArrayType",
	2197:  "SessionDiagnosticsVariableType",
	2243:  "SessionSecurityDiagnosticsArrayType",
	2244:  "SessionSecurityDiagnosticsType",
	2365:  "DataItemType",
	2368:  "AnalogItemType",
	2372:  "DiscreteItemType",
	2373:  "TwoStateDiscreteType",
	2376:  "MultiStateDiscreteType",
	2380:  "ProgramDiagnosticType",
	2755:  "StateVariableType",
	2760:  "FiniteStateVariableType",
	2762:  "TransitionVariableType",
	2767:  "FiniteTransitionVariableType",
	3051:  "BuildInfoType",
	8995:  "TwoStateVariableType",
	9002:  "ConditionVariableType",
	11238: "MultiStateValueDiscreteType",
	11487: "OptionSetType",
	12021: "ArrayItemType",
	12029: "YArrayItemType",
	12038: "XYArrayItemType",
	12047: "ImageItemType",
	12057: "CubeItemType",
	12068: "NDimensionArrayItemType",
	15113: "GuardVariableType",
	15128: "ExpressionGuardVariableType",
	15317: "ElseGuardVariableType",
	15318: "BaseAnalogType",
	15383: "ProgramDiagnostic2Type",
	16309: "SelectionListType",
	17277: "AlarmRateVariableType",
	17497: "AnalogUnitType",
	17570: "AnalogUnitRangeType",
	17709: "RationalNumberType",
	17714: "VectorType",
	17716: "ThreeDVectorType",
	17986: "AudioVariableType",
	18772: "CartesianCoordinatesType",
	18774: "ThreeDCartesianCoordinatesType",
	18779: "OrientationType",
	18781: "ThreeDOrientationType",
	18786: "FrameType",
	18791: "ThreeDFrameType",
	19077: "MultiStateDictionaryEntryDiscreteBaseType",
	19084: "MultiStateDictionaryEntryDiscreteType",
	19725: "PubSubDiagnosticsCounterType",
	32244: "AlarmStateVariableType",
	32657: "ReferenceDescriptionVariableType",
}
