// Copyright 2018-2019 opcua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

// Code generated by cmd/service. DO NOT EDIT!

package ua

type DataSetReaderDataType struct {
	Name                    string
	Enabled                 bool
	PublisherID             *Variant
	WriterGroupID           uint16
	DataSetWriterID         uint16
	DataSetMetaData         *DataSetMetaDataType
	DataSetFieldContentMask DataSetFieldContentMask
	MessageReceiveTimeout   float64
	KeyFrameCount           uint32
	HeaderLayoutURI         string
	SecurityMode            MessageSecurityMode
	SecurityGroupID         string
	SecurityKeyServices     []*EndpointDescription
	DataSetReaderProperties []*KeyValuePair
	TransportSettings       *ExtensionObject
	MessageSettings         *ExtensionObject
	SubscribedDataSet       *ExtensionObject
}
