// Copyright 2018-2019 opcua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

// Code generated by cmd/service. DO NOT EDIT!

package ua

type DataSetWriterDataType struct {
	Name                    string
	Enabled                 bool
	DataSetWriterID         uint16
	DataSetFieldContentMask DataSetFieldContentMask
	KeyFrameCount           uint32
	DataSetName             string
	DataSetWriterProperties []*KeyValuePair
	TransportSettings       *ExtensionObject
	MessageSettings         *ExtensionObject
}
