// Copyright 2018-2019 opcua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

// Code generated by cmd/service. DO NOT EDIT!

package ua

type FieldMetaData struct {
	Name            string
	Description     *LocalizedText
	FieldFlags      DataSetFieldFlags
	BuiltInType     uint8
	DataType        *NodeID
	ValueRank       int32
	ArrayDimensions []uint32
	MaxStringLength uint32
	DataSetFieldID  *GUID
	Properties      []*KeyValuePair
}
