// Copyright 2018-2019 opcua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

// Code generated by cmd/service. DO NOT EDIT!

package ua

type MethodNode struct {
	NodeID              *NodeID
	NodeClass           NodeClass
	BrowseName          *QualifiedName
	DisplayName         *LocalizedText
	Description         *LocalizedText
	WriteMask           uint32
	UserWriteMask       uint32
	RolePermissions     []*RolePermissionType
	UserRolePermissions []*RolePermissionType
	AccessRestrictions  uint16
	References          []*ReferenceNode
	Executable          bool
	UserExecutable      bool
}
