// Copyright 2018-2019 opcua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

// Code generated by cmd/service. DO NOT EDIT!

package ua

type PublishedVariableDataType struct {
	PublishedVariable    *NodeID
	AttributeID          uint32
	SamplingIntervalHint float64
	DeadbandType         uint32
	DeadbandValue        float64
	IndexRange           string
	SubstituteValue      *Variant
	MetaDataProperties   []*QualifiedName
}
