// Copyright 2018-2019 opcua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

// Code generated by cmd/service. DO NOT EDIT!

package ua

import "time"

type SessionDiagnosticsDataType struct {
	SessionID                          *NodeID
	SessionName                        string
	ClientDescription                  *ApplicationDescription
	ServerURI                          string
	EndpointURL                        string
	LocaleIDs                          []string
	ActualSessionTimeout               float64
	MaxResponseMessageSize             uint32
	ClientConnectionTime               time.Time
	ClientLastContactTime              time.Time
	CurrentSubscriptionsCount          uint32
	CurrentMonitoredItemsCount         uint32
	CurrentPublishRequestsInQueue      uint32
	TotalRequestCount                  *ServiceCounterDataType
	UnauthorizedRequestCount           uint32
	ReadCount                          *ServiceCounterDataType
	HistoryReadCount                   *ServiceCounterDataType
	WriteCount                         *ServiceCounterDataType
	HistoryUpdateCount                 *ServiceCounterDataType
	CallCount                          *ServiceCounterDataType
	CreateMonitoredItemsCount          *ServiceCounterDataType
	ModifyMonitoredItemsCount          *ServiceCounterDataType
	SetMonitoringModeCount             *ServiceCounterDataType
	SetTriggeringCount                 *ServiceCounterDataType
	DeleteMonitoredItemsCount          *ServiceCounterDataType
	CreateSubscriptionCount            *ServiceCounterDataType
	ModifySubscriptionCount            *ServiceCounterDataType
	SetPublishingModeCount             *ServiceCounterDataType
	PublishCount                       *ServiceCounterDataType
	RepublishCount                     *ServiceCounterDataType
	TransferSubscriptionsCount         *ServiceCounterDataType
	DeleteSubscriptionsCount           *ServiceCounterDataType
	AddNodesCount                      *ServiceCounterDataType
	AddReferencesCount                 *ServiceCounterDataType
	DeleteNodesCount                   *ServiceCounterDataType
	DeleteReferencesCount              *ServiceCounterDataType
	BrowseCount                        *ServiceCounterDataType
	BrowseNextCount                    *ServiceCounterDataType
	TranslateBrowsePathsToNodeIDsCount *ServiceCounterDataType
	QueryFirstCount                    *ServiceCounterDataType
	QueryNextCount                     *ServiceCounterDataType
	RegisterNodesCount                 *ServiceCounterDataType
	UnregisterNodesCount               *ServiceCounterDataType
}
