// Copyright 2018-2019 opcua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

// Code generated by cmd/service. DO NOT EDIT!

package ua

type VariableAttributes struct {
	SpecifiedAttributes     uint32
	DisplayName             *LocalizedText
	Description             *LocalizedText
	WriteMask               uint32
	UserWriteMask           uint32
	Value                   *Variant
	DataType                *NodeID
	ValueRank               int32
	ArrayDimensions         []uint32
	AccessLevel             uint8
	UserAccessLevel         uint8
	MinimumSamplingInterval float64
	Historizing             bool
}
